//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscapeFromTarkovLoadout.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscapeFromTarkovLoadout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_6B13_assault {
            get {
                object obj = ResourceManager.GetObject("Armor_6B13-assault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_6B13_M_Killa {
            get {
                object obj = ResourceManager.GetObject("Armor_6B13_M_Killa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_6B2_armor {
            get {
                object obj = ResourceManager.GetObject("Armor_6B2_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_6B23_1_digital_flora {
            get {
                object obj = ResourceManager.GetObject("Armor_6B23-1_digital_flora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_6B23_2 {
            get {
                object obj = ResourceManager.GetObject("Armor_6B23-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_6B43_Zabralo_Sh_6A_Fort {
            get {
                object obj = ResourceManager.GetObject("Armor_6B43_Zabralo-Sh_6A_Fort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_BNTI_Gzhel_K {
            get {
                object obj = ResourceManager.GetObject("Armor_BNTI_Gzhel-K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_BNTI_Kirasa_N {
            get {
                object obj = ResourceManager.GetObject("Armor_BNTI_Kirasa-N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_BNTI_Korund_VM {
            get {
                object obj = ResourceManager.GetObject("Armor_BNTI_Korund-VM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_FORT_Defender_2 {
            get {
                object obj = ResourceManager.GetObject("Armor_FORT_Defender-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_FORT_Redut_M {
            get {
                object obj = ResourceManager.GetObject("Armor_FORT_Redut-M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_Highcom_Trooper_TFO {
            get {
                object obj = ResourceManager.GetObject("Armor_Highcom_Trooper_TFO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_IOTV_Gen4_assault {
            get {
                object obj = ResourceManager.GetObject("Armor_IOTV_Gen4_assault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_IOTV_Gen4_full {
            get {
                object obj = ResourceManager.GetObject("Armor_IOTV_Gen4_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_IOTV_Gen4_high_mobility {
            get {
                object obj = ResourceManager.GetObject("Armor_IOTV_Gen4_high_mobility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_LBT_6094A_Slick {
            get {
                object obj = ResourceManager.GetObject("Armor_LBT_6094A_Slick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_MF_UNTAR {
            get {
                object obj = ResourceManager.GetObject("Armor_MF-UNTAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_Module_3M {
            get {
                object obj = ResourceManager.GetObject("Armor_Module-3M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_PACA_Soft_Armor {
            get {
                object obj = ResourceManager.GetObject("Armor_PACA_Soft_Armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_Zhuk_3_Press_Armor {
            get {
                object obj = ResourceManager.GetObject("Armor_Zhuk-3_Press_Armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_Zhuk_6a {
            get {
                object obj = ResourceManager.GetObject("Armor_Zhuk-6a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_3V_G_Paratus {
            get {
                object obj = ResourceManager.GetObject("Backpack_3V_G_Paratus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_6SH118_Raid {
            get {
                object obj = ResourceManager.GetObject("Backpack_6SH118_Raid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Ana_Beta_2 {
            get {
                object obj = ResourceManager.GetObject("Backpack_Ana_Beta_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Camelback_Tri_Zip {
            get {
                object obj = ResourceManager.GetObject("Backpack_Camelback_Tri-Zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Duffle_bag {
            get {
                object obj = ResourceManager.GetObject("Backpack_Duffle_bag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Eberlestock_F4_Terminator {
            get {
                object obj = ResourceManager.GetObject("Backpack_Eberlestock_F4_Terminator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Eberlestock_F5_Switchable {
            get {
                object obj = ResourceManager.GetObject("Backpack_Eberlestock_F5_Switchable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Flyye_MBSS {
            get {
                object obj = ResourceManager.GetObject("Backpack_Flyye_MBSS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_LBT_2670_Slim_Field_Med {
            get {
                object obj = ResourceManager.GetObject("Backpack_LBT-2670_Slim_Field_Med", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_LBT_8005A_Day_pack {
            get {
                object obj = ResourceManager.GetObject("Backpack_LBT-8005A_Day_pack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_LK_3F_Transfer_tourist {
            get {
                object obj = ResourceManager.GetObject("Backpack_LK_3F_Transfer_tourist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Mystery_Ranch_Blackjack_50 {
            get {
                object obj = ResourceManager.GetObject("Backpack_Mystery_Ranch_Blackjack_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Oakley_Mechanism {
            get {
                object obj = ResourceManager.GetObject("Backpack_Oakley_Mechanism", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Pilgrim_tourist {
            get {
                object obj = ResourceManager.GetObject("Backpack_Pilgrim_tourist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Sanitar_bag {
            get {
                object obj = ResourceManager.GetObject("Backpack_Sanitar_bag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Scav_Backpack {
            get {
                object obj = ResourceManager.GetObject("Backpack_Scav_Backpack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_SS0_Attack_2_Raid {
            get {
                object obj = ResourceManager.GetObject("Backpack_SS0_Attack_2_Raid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Tactical_sling {
            get {
                object obj = ResourceManager.GetObject("Backpack_Tactical_sling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Transformer_T_bag {
            get {
                object obj = ResourceManager.GetObject("Backpack_Transformer_T-bag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_VKBO_Army_bag {
            get {
                object obj = ResourceManager.GetObject("Backpack_VKBO_Army_bag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backpack_Wartech_Berkut_VV_102 {
            get {
                object obj = ResourceManager.GetObject("Backpack_Wartech_Berkut_VV-102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EscapeFromTarkovBackgroundCharacter {
            get {
                object obj = ResourceManager.GetObject("EscapeFromTarkovBackgroundCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EscapeFromTarkovBackgroundGetReady {
            get {
                object obj = ResourceManager.GetObject("EscapeFromTarkovBackgroundGetReady", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EscapeFromTarkovBackgroundInfo {
            get {
                object obj = ResourceManager.GetObject("EscapeFromTarkovBackgroundInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_6B47_Ratnik_BSh {
            get {
                object obj = ResourceManager.GetObject("Headwear_6B47_Ratnik-BSh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Airframe {
            get {
                object obj = ResourceManager.GetObject("Headwear_Airframe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Altyn {
            get {
                object obj = ResourceManager.GetObject("Headwear_Altyn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Armasight_NVG_mask {
            get {
                object obj = ResourceManager.GetObject("Headwear_Armasight_NVG_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Army_cap {
            get {
                object obj = ResourceManager.GetObject("Headwear_Army_cap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Bandana {
            get {
                object obj = ResourceManager.GetObject("Headwear_Bandana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Baseball_cap {
            get {
                object obj = ResourceManager.GetObject("Headwear_Baseball_cap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Beanie {
            get {
                object obj = ResourceManager.GetObject("Headwear_Beanie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_BEAR_Baseball {
            get {
                object obj = ResourceManager.GetObject("Headwear_BEAR_Baseball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_BEAR_Baseball_Black {
            get {
                object obj = ResourceManager.GetObject("Headwear_BEAR_Baseball_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Beret_black {
            get {
                object obj = ResourceManager.GetObject("Headwear_Beret_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Beret_blue {
            get {
                object obj = ResourceManager.GetObject("Headwear_Beret_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Beret_olive {
            get {
                object obj = ResourceManager.GetObject("Headwear_Beret_olive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_BNTI_LSHZ_2DTM {
            get {
                object obj = ResourceManager.GetObject("Headwear_BNTI_LSHZ-2DTM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Cowboy_Hat {
            get {
                object obj = ResourceManager.GetObject("Headwear_Cowboy_Hat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_DEVTAC_Ronin {
            get {
                object obj = ResourceManager.GetObject("Headwear_DEVTAC_Ronin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Diamond_Age_Bastion {
            get {
                object obj = ResourceManager.GetObject("Headwear_Diamond_Age_Bastion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Door_Kicker {
            get {
                object obj = ResourceManager.GetObject("Headwear_Door_Kicker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_EmerCom_cap {
            get {
                object obj = ResourceManager.GetObject("Headwear_EmerCom_cap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Galvion_Caiman {
            get {
                object obj = ResourceManager.GetObject("Headwear_Galvion_Caiman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Highcom_Striker_ACHHC_IIIA {
            get {
                object obj = ResourceManager.GetObject("Headwear_Highcom_Striker_ACHHC_IIIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Highcom_Striker_ULACH_IIIA {
            get {
                object obj = ResourceManager.GetObject("Headwear_Highcom_Striker_ULACH_IIIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Jack_o_lantern_pumpkin {
            get {
                object obj = ResourceManager.GetObject("Headwear_Jack-o-lantern_pumpkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Kiver_M {
            get {
                object obj = ResourceManager.GetObject("Headwear_Kiver-M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Kolpak_1S {
            get {
                object obj = ResourceManager.GetObject("Headwear_Kolpak-1S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Kotton_Beanie {
            get {
                object obj = ResourceManager.GetObject("Headwear_Kotton_Beanie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_LZSh_light {
            get {
                object obj = ResourceManager.GetObject("Headwear_LZSh_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Maska_1Sch_Killa {
            get {
                object obj = ResourceManager.GetObject("Headwear_Maska_1Sch_Killa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Miltec_Panama {
            get {
                object obj = ResourceManager.GetObject("Headwear_Miltec_Panama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_MSA_ACH_TC_2001 {
            get {
                object obj = ResourceManager.GetObject("Headwear_MSA_ACH_TC-2001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_MSA_ACH_TC_2002 {
            get {
                object obj = ResourceManager.GetObject("Headwear_MSA_ACH_TC-2002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_MSA_Gallet_TC_800 {
            get {
                object obj = ResourceManager.GetObject("Headwear_MSA_Gallet_TC_800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Ops_Core_Fast_MT {
            get {
                object obj = ResourceManager.GetObject("Headwear_Ops_Core_Fast_MT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Police_cap {
            get {
                object obj = ResourceManager.GetObject("Headwear_Police_cap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Pompon {
            get {
                object obj = ResourceManager.GetObject("Headwear_Pompon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_PSH_97_Djeta {
            get {
                object obj = ResourceManager.GetObject("Headwear_PSH-97_Djeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Shmaska_Ski_hat_with_holes {
            get {
                object obj = ResourceManager.GetObject("Headwear_Shmaska_Ski_hat_with_holes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_SHPM_Firefighter {
            get {
                object obj = ResourceManager.GetObject("Headwear_SHPM_Firefighter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Soft_tank_crew_helmet_TSH_4M_L {
            get {
                object obj = ResourceManager.GetObject("Headwear_Soft_tank_crew_helmet_TSH-4M-L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_SSh_68 {
            get {
                object obj = ResourceManager.GetObject("Headwear_SSh-68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_SSSh_95_Sfera_S {
            get {
                object obj = ResourceManager.GetObject("Headwear_SSSh-95_Sfera-S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Tac_Kek_Fast_MT_Helmet {
            get {
                object obj = ResourceManager.GetObject("Headwear_Tac-Kek_Fast_MT_Helmet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Tactical_Fleece_hat {
            get {
                object obj = ResourceManager.GetObject("Headwear_Tactical_Fleece_hat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Team_Wendy_EXFIL {
            get {
                object obj = ResourceManager.GetObject("Headwear_Team_Wendy_EXFIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_UNTAR {
            get {
                object obj = ResourceManager.GetObject("Headwear_UNTAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_USEC_Baseball {
            get {
                object obj = ResourceManager.GetObject("Headwear_USEC_Baseball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_USEC_Baseball_Black {
            get {
                object obj = ResourceManager.GetObject("Headwear_USEC_Baseball_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Ushanka_ear_flap {
            get {
                object obj = ResourceManager.GetObject("Headwear_Ushanka_ear-flap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_UX_PRO {
            get {
                object obj = ResourceManager.GetObject("Headwear_UX_PRO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Vulkan_5_LShZ_5 {
            get {
                object obj = ResourceManager.GetObject("Headwear_Vulkan-5_LShZ-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_Wilcox_Skull_Lock_head_mount {
            get {
                object obj = ResourceManager.GetObject("Headwear_Wilcox_Skull_Lock_head_mount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Headwear_ZSh1_2M {
            get {
                object obj = ResourceManager.GetObject("Headwear_ZSh1-2M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info_logo {
            get {
                object obj = ResourceManager.GetObject("Info_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map_Customs {
            get {
                object obj = ResourceManager.GetObject("Map_Customs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map_Factory {
            get {
                object obj = ResourceManager.GetObject("Map_Factory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map_Interchange {
            get {
                object obj = ResourceManager.GetObject("Map_Interchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map_Reserve {
            get {
                object obj = ResourceManager.GetObject("Map_Reserve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map_Shoreline {
            get {
                object obj = ResourceManager.GetObject("Map_Shoreline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map_TheLab {
            get {
                object obj = ResourceManager.GetObject("Map_TheLab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map_Woods {
            get {
                object obj = ResourceManager.GetObject("Map_Woods", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_ANA_Tactical_Alpha {
            get {
                object obj = ResourceManager.GetObject("Rig_ANA_Tactical_Alpha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_511_TacTec {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_511_TacTec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_6B3TM_01M {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_6B3TM-01M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_6B5_15_Zh {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_6B5-15-Zh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_6B5_16_Zh_86 {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_6B5-16-Zh-86", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_ANA_Tactical_M1 {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_ANA_Tactical_M1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_ANA_Tactical_M2 {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_ANA_Tactical_M2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_Ars_Arma_A18 {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_Ars_Arma_A18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_Ars_Arma_CPC_MOD_2 {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_Ars_Arma_CPC_MOD_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_Crye_Precission_AVS {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_Crye_Precission_AVS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Armored_Wartech_TV_110 {
            get {
                object obj = ResourceManager.GetObject("Rig_Armored_Wartech_TV-110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Belt_A_Belt_B {
            get {
                object obj = ResourceManager.GetObject("Rig_Belt-A_Belt-B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Blackhawk_Commando {
            get {
                object obj = ResourceManager.GetObject("Rig_Blackhawk_Commando", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_BlackRock {
            get {
                object obj = ResourceManager.GetObject("Rig_BlackRock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Direct_Action_Thunderbolt {
            get {
                object obj = ResourceManager.GetObject("Rig_Direct_Action_Thunderbolt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Haley_Strategic_D3CRX {
            get {
                object obj = ResourceManager.GetObject("Rig_Haley_Strategic_D3CRX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_LBT_1961A_Load_Bearing {
            get {
                object obj = ResourceManager.GetObject("Rig_LBT-1961A_Load_Bearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Scav_vest {
            get {
                object obj = ResourceManager.GetObject("Rig_Scav_vest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_SOE_Micro_rig {
            get {
                object obj = ResourceManager.GetObject("Rig_SOE_Micro_rig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Spiritus_System_Bank_Robber {
            get {
                object obj = ResourceManager.GetObject("Rig_Spiritus_System_Bank_Robber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Splav_Tarzan_M22 {
            get {
                object obj = ResourceManager.GetObject("Rig_Splav_Tarzan_M22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Triton_M43_A {
            get {
                object obj = ResourceManager.GetObject("Rig_Triton_M43-A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_UMTBS_6sh112_Scout_sniper {
            get {
                object obj = ResourceManager.GetObject("Rig_UMTBS_6sh112_Scout-sniper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Velocity_MPPV {
            get {
                object obj = ResourceManager.GetObject("Rig_Velocity_MPPV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Wartech_MK3_TV_104 {
            get {
                object obj = ResourceManager.GetObject("Rig_Wartech_MK3_TV-104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rig_Wartech_TV_109_TV_106 {
            get {
                object obj = ResourceManager.GetObject("Rig_Wartech_TV-109_TV-106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultCarbine_OP_SKS {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultCarbine_OP-SKS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultCarbine_SKS {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultCarbine_SKS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultCarbine_Vepr_Hunter {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultCarbine_Vepr_Hunter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_ADAR_2_15 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_ADAR_2-15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AK_101 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AK-101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AK_102 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AK-102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AK_103 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AK-103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AK_104 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AK-104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AK_105 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AK-105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AK_74 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AK-74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AK_74M {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AK-74M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AK_74N {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AK-74N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKM {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKMN {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKMN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKMS {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKMS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKMSN {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKMSN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKS_74 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKS-74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKS_74N {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKS-74N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKS_74U {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKS-74U", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKS_74UB {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKS-74UB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AKS_74UN {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AKS-74UN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_AS_VAL {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_AS_VAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_ASh_12 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_ASh-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_DT_MDR_556 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_DT_MDR_556", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_DT_MDR_762 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_DT_MDR_762", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_HK_416A5 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_HK_416A5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_Kel_Tec_RFB {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_Kel-Tec_RFB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_M4A1 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_M4A1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_SA_58 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_SA-58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_TX_15_DML {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_TX-15_DML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_Vepr_AKM_VPO_209 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_Vepr_AKM_VPO-209", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_AssaultRifle_Vepr_KM_VPO_136 {
            get {
                object obj = ResourceManager.GetObject("Weapon_AssaultRifle_Vepr_KM_VPO-136", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_DMR_M1A {
            get {
                object obj = ResourceManager.GetObject("Weapon_DMR_M1A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_DMR_RSASS {
            get {
                object obj = ResourceManager.GetObject("Weapon_DMR_RSASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_DMR_SR_25 {
            get {
                object obj = ResourceManager.GetObject("Weapon_DMR_SR-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_DMR_SVDS {
            get {
                object obj = ResourceManager.GetObject("Weapon_DMR_SVDS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_DMR_VSS {
            get {
                object obj = ResourceManager.GetObject("Weapon_DMR_VSS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_LightMachineGun_RPK_16 {
            get {
                object obj = ResourceManager.GetObject("Weapon_LightMachineGun_RPK-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_APB {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_APB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_APS {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_APS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_FN_5_7 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_FN_5-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_Glock_17 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_Glock_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_Glock_18C {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_Glock_18C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_M1911A1 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_M1911A1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_M45A1 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_M45A1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_M9A3 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_M9A3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_MP_443_Grach {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_MP-443_Grach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_P226R {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_P226R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_PB {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_PB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_PM {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_PM_t {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_PM_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_SR_1MP {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_SR-1MP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_TT {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_TT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Pistol_TT_Glod {
            get {
                object obj = ResourceManager.GetObject("Weapon_Pistol_TT_Glod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Shotgun_590A1 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Shotgun_590A1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Shotgun_KS_23M {
            get {
                object obj = ResourceManager.GetObject("Weapon_Shotgun_KS-23M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Shotgun_M870 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Shotgun_M870", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Shotgun_MP_133 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Shotgun_MP-133", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Shotgun_MP_153 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Shotgun_MP-153", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Shotgun_Saiga_12 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Shotgun_Saiga-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_Shotgun_TOZ_106 {
            get {
                object obj = ResourceManager.GetObject("Weapon_Shotgun_TOZ-106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SniperRifle_DVL_10 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SniperRifle_DVL-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SniperRifle_M700 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SniperRifle_M700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SniperRifle_Mosin {
            get {
                object obj = ResourceManager.GetObject("Weapon_SniperRifle_Mosin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SniperRifle_Mosin_inf {
            get {
                object obj = ResourceManager.GetObject("Weapon_SniperRifle_Mosin_inf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SniperRifle_SV_98 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SniperRifle_SV-98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SniperRifle_T_5000 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SniperRifle_T-5000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SniperRifle_VOP_215 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SniperRifle_VOP-215", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_MP5 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_MP5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_MP5K_N {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_MP5K-N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_MP7A1 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_MP7A1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_MP7A2 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_MP7A2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_MP9 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_MP9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_MP9_N {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_MP9-N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_MPX {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_MPX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_P90 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_P90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_PP_19_01 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_PP-19-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_PP_9_Klin {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_PP-9_Klin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_PP_91_01_Kedr_B {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_PP-91-01_Kedr-B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_PP_91_Kedr {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_PP-91_Kedr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_PPSH_41 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_PPSH-41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weapon_SubMachineGun_Saiga_9 {
            get {
                object obj = ResourceManager.GetObject("Weapon_SubMachineGun_Saiga-9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
